### ISSUE TITLE
Ux - Get Current/Pending Users

### ISSUE THREAD

**Issue by ted-marozzi** [programmers-from-the-same-company/company-website#5]
User can't see that the current members are being retrieved, need to add a loading spinner.

Also pending members should be shown first so on mobile they are at the top and a user can verify easily that the membership has been sent.

**Comment by GauravMenezes-Dev** [comment]
Raised PR for the same, please review: https://github.com/programmers-from-the-same-company/company-website/pull/7

**Comment by ted-marozzi** [comment]
Fixed by pr
